### ISSUE TITLE
chat selector adaptor

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#11]
There is this selector adaptor function, it seems to work fine. But it returns a warning.

Please try to have some dialogues and it prints this:
item 0 <class 'int'>
demo-chatbot-v4.0/.venv/lib/python3.11/site-packages/taipy/gui/utils/_adapter.py:143: TaipyGuiWarning: Cannot run adapter for tpec_TpExPr_selected_conv_TPMDL_5:
'int' object is not subscriptable
  _warn(f"Cannot run adapter for {var_name}", e)

1. Why is that?
2. Could you explain in details, why this selector adapter function is called twice per action?

**Comment by figoyouwei** [comment]
this happens when the user selects a conversation, or in my new code, called session.

**Comment by figoyouwei** [comment]
How about we have a google meet, tonight?

**Comment by figoyouwei** [comment]
ok, I better understood selector

1.adapter returns the string for display...
2.type wraps the data model
3.on_change is actually on_click and returns the content to value

**Comment by AlexandreSajus** [comment]
Do you still need help with this?

**Comment by figoyouwei** [comment]
yes, the bug and warning message was there in "your" code, so please have at least a run, thanks.

**Comment by figoyouwei** [comment]
ok, I wrote some data models to run selector ok, so I close it now.
