### ISSUE TITLE
Work with database

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#12]
Hey,

Today I extended on your code and built some data models to better manage the chat messages and sessions. 
https://github.com/figoyouwei/taipy_success/blob/main/chatbot/models/chat.py

Next week I will be implementing the database part, is there any advanced design by Taipy for me to utilize when working with database?

**Comment by AlexandreSajus** [comment]
It depends on what the database will be used for. Will it be used only for writing and reading a message log? Will it be for a single user or multiple? How many messages will be stored? How many reads do you expect per hour? Which web service will you be using?

We do have some tooling around data integration, but it is centered around managing data pipelines, orchestrating tasks, modifying inputs, and visualizing outputs. It might not make sense here.
