### ISSUE TITLE
pop-up window

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#14]
Hi,

How can a developer realize a pop-up window function? My understand is that this pop-up window is also a tgb.Page object and its size can be controlled. Any sample code?

**Comment by AlexandreSajus** [comment]
Sure! You can use tgb.dialog to create a pop-up window: https://docs.taipy.io/en/latest/manuals/gui/viselements/dialog/
You can then put any other visual elements within the pop-up window.

Here is a simple code sample where I open the pop-up window with a button and put some text into it:
![image](https://github.com/user-attachments/assets/6435fcd4-91d3-4eb5-b26d-8014a15f0017)

```python
from taipy.gui import Gui, State
import taipy.gui.builder as tgb

show_dialog = False
some_content = "Hello, world!"


def open_dialog(state: State):
    state.show_dialog = True


with tgb.Page() as page:
    tgb.button("Open Pop-up", on_action=open_dialog)
    with tgb.dialog(
        "{show_dialog}", on_action="{lambda s: s.assign('show_dialog', False)}"
    ):
        tgb.text("{some_content}")

if __name__ == "__main__":
    Gui(page=page).run()
```

**Comment by figoyouwei** [comment]
The code returns this RuntimeError
https://github.com/figoyouwei/taipy_success/blob/main/KnowledgeBase/popup.py

`RuntimeError: Can't use Context Manager for control type 'dialog'`

**Comment by figoyouwei** [comment]
ok, the code runs fine with v4.0.0dev2. Let's move to further questions, e.g. I see a <h2> is native with the dialog component, how to set it invisible? Does it have to be done with css?
<img width="536" alt="Screenshot 2024-09-18 at 13 53 51" src="https://github.com/user-attachments/assets/924f5111-c9cb-458a-98fb-765d54798b14">

**Comment by figoyouwei** [comment]
ok, the code runs fine with v4.0.0dev2. Let's move to further questions:
e.g. I see that the h2 is native with the dialog component, how to set it invisible? Does it have to be done with css?
<img width="536" alt="Screenshot 2024-09-18 at 13 53 51" src="https://github.com/user-attachments/assets/d31e3d6c-a473-4c77-be3d-10c8bd120c5b">

**Comment by AlexandreSajus** [comment]
It has to be done through CSS, here is an example that works:

![image](https://github.com/user-attachments/assets/670a2a54-c468-4f46-aa12-beed9996cd30)

In `dialog.py`:
```python
from taipy.gui import Gui, State
import taipy.gui.builder as tgb

show_dialog = False
some_content = "Hello, this is a pop-up"


# Initialize the state with 'show_dialog' to False
def on_init(state: State):
    state.show_dialog = False
    state.some_content = "Hello, this is a pop-up dialog!"


# Function to open the dialog
def open_dialog(state: State):
    state.show_dialog = True


# Function to close the dialog
def close_dialog(state: State):
    state.show_dialog = False


# Build the page layout
with tgb.Page() as page:
    # Button to open the dialog
    tgb.button("Open Pop-up", on_action=open_dialog)

    # Dialog that will pop up when 'show_dialog' is True
    with tgb.dialog("{show_dialog}", on_action=close_dialog):
        tgb.text("{some_content}")
        tgb.button("Close", on_action=close_dialog)

# Running the GUI
if __name__ == "__main__":
    Gui(page=page).run()
```

In `dialog.css`:
```css
.css-16o21sr {
    visibility: hidden;
    padding: 0;
    height: 0;
}
```

**Comment by figoyouwei** [comment]
Thanks.
