### ISSUE TITLE
How to center navbar with tgb

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#16]
Hi,

I know how to center navbar with Markdown, but how to do it with tgb? Please check, thanks.
https://github.com/figoyouwei/taipy_success/blob/main/apps/yfin/pages/home.py

<img width="1327" alt="Screenshot 2024-09-11 at 16 03 33" src="https://github.com/user-attachments/assets/ddeaed0b-2a0b-4656-bcf6-5c50dee35c57">

**Comment by AlexandreSajus** [comment]
Here is an example that works:

In main.py:
```python
from taipy import Gui
import taipy.gui.builder as tgb

with tgb.Page() as root_page:
    tgb.navbar(class_name="navbar")
    tgb.text("# Multi-page application", mode="md")

with tgb.Page() as page_1:
    tgb.text("## This is page 1", mode="md")
with tgb.Page() as page_2:
    tgb.text("## This is page 2", mode="md")

pages = {"/": root_page, "page1": page_1, "page2": page_2}
Gui(pages=pages).run()
```

In main.css:
```css
.navbar {
    margin: auto;
}
```

**Comment by figoyouwei** [comment]
Thanks.
