### ISSUE TITLE
Problem with running tp.Scheduler

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#21]
Hey,

I am running this code Florian gave me in August.
https://github.com/figoyouwei/taipy_success/blob/main/scheduler/hello_scheduler.py

It returns this on the page, please check, thanks.
<img width="806" alt="Screenshot 2024-09-20 at 10 16 18" src="https://github.com/user-attachments/assets/f140e846-5d93-428a-8ab5-1a46ebc46856">

**Comment by AlexandreSajus** [comment]
It works fine with your version of Taipy Enterprise:
![image](https://github.com/user-attachments/assets/1e08c282-cbfe-49f9-8928-4a95e0a12dc4)

Please make sure you are running this code from a clean virtual environment:
https://docs.astral.sh/uv/pip/environments/#creating-a-virtual-environment

**Comment by figoyouwei** [comment]
OK, it runs fine. I will open new issue when extending this.
