### ISSUE TITLE
personwebsite: root page jump issue

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#24]
Hi,

It is an old but newly opened issue, please check the code I adopted from yours.
https://github.com/figoyouwei/taipy_success/tree/main/personwebsite

Following this code, it works "almost" perfect. When I put it in production with a domain, e.g. `www.personx.com`
It automatically jumps to `www.personx.com/about` which is perfect.

BUT
By some browser and particularly mobile browser e.g. on my iPhone Safari, it stuck at `www.personx.com` which is empty like this
<img width="1313" alt="Screenshot 2024-10-01 at 16 26 39" src="https://github.com/user-attachments/assets/85752ca9-7ddc-4f9d-8a1b-a93500e87573">

Any elegant way to make it perfect?

**Comment by AlexandreSajus** [comment]
Hey Youwei! Taipy is not really made for mobile applications but let me ask R&D and come back to you

**Comment by AlexandreSajus** [comment]
Unfortunately we are not sure where this is coming from. What are you using for deployment and especially to redirect a public URL to your machine? Maybe you could use the service you are using to redirect `www.personx.com` to `www.personx.com/about`

**Comment by figoyouwei** [comment]
OK, never mind the url jump. 

This is my very preliminary data freelancing site, solely using Taipy. 
https://www.datauv.asia/

And actually the community likes it very much. 
<img width="774" alt="Screenshot 2024-10-07 at 17 14 54" src="https://github.com/user-attachments/assets/2809772e-1bbe-4c18-9dff-f9b0c4ee1699">

So if you could make the mobile view a little better and responsive, I will stick with it without bringing in Django and this Taipy solution will be further promoted inside the freelancing community.

**Comment by AlexandreSajus** [comment]
Sure! Where is the code for this application? What did you use to deploy it? Maybe we can deploy this on our side to improve performance
