### ISSUE TITLE
Task with commit to database error

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#3]
I added a new task task_cfg_yfin_cmt, it returns error. I have verify the normal workflow, it is fine.
https://github.com/figoyouwei/taipy_success/blob/main/app/scenarios/yfin_spx.py

**Comment by figoyouwei** [comment]
I notice that the scenario run was actually successful, data written into the database table, but it prints out this
TypeError: Object of type method is not JSON serializable

**Comment by figoyouwei** [comment]
TypeError: Object of type method is not JSON serializable

**Comment by FlorianJacta** [comment]
And what if you try to create your function for *db_manager.commit_data*. Like:

```python
def commit_data(...):
    # use db_manager.commit_data
    return what_you_want
```

Taipy Tasks deal with functions and not method.

**Comment by figoyouwei** [comment]
Cool, it returns no error after some code like this.
