### ISSUE TITLE
minor UI issue by chat scroll bar

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#31]
Hey,

In addition to the height bug of chat-frame, there is a minor UI issue. 

You see below? When you scroll, the scroll bar is currently covering the user icon, please make the UI more friendly and professional, thanks.
<img width="766" alt="Screenshot 2024-10-28 at 15 06 00" src="https://github.com/user-attachments/assets/b9e31b72-de93-4ec8-9637-38ccfa2ec349">

**Comment by AlexandreSajus** [comment]
Adding this line to `main.css` fixes the issue:
```css
.taipy-chat > .MuiGrid2-root {
    padding-right: 10px;
}
```

![image](https://github.com/user-attachments/assets/391fbea3-f452-4326-af29-39d9a0a30993)

**Comment by figoyouwei** [comment]
Thanks.
