### ISSUE TITLE
chat async

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#32]
Hey,

I am optimizing the code with async for better performance. Here, on the `evaluate` function
https://github.com/figoyouwei/taipy_success/blob/main/chatbot/pages/chat.py

How to make it work? 
Or it is not necessary, all the asynchronous functionality is handled by Taipy, already?

**Comment by AlexandreSajus** [comment]
This should not be necessary. Taipy already separates front-end and back-end work on different threads to optimize performance. If you have a computation that takes a lot of time, Taipy has pre-built functions to offload computations to another thread and wait for their results: https://docs.taipy.io/en/latest/tutorials/articles/long_callbacks/
