### ISSUE TITLE
Enterprise ImportError

### ISSUE THREAD

**Issue by figoyouwei** [figoyouwei/taipy_success#6]
Hi,

I was running this same script, v3.1.0 is fine
https://github.com/figoyouwei/taipy_success/blob/main/scenarios/job_execution.py

but the newly installed enterprise version returns this error
ImportError: bad magic number in 'taipy.enterprise': b'o\r\r\n'

**Comment by FlorianJacta** [comment]
Hi,

Could you give us how you installed Enterprise, how you run it, and this information?

- OS:
- Python version:
- pip version:

**Comment by figoyouwei** [comment]
>> sw_vers
ProductName: macOS
ProductVersion: 14.2.1
BuildVersion: 23C71

>> python --version
Python 3.12.3

>> poetry --version
Poetry (version 1.8.2)

**Comment by figoyouwei** [comment]
# sw_vers
ProductName: macOS
ProductVersion: 14.2.1
BuildVersion: 23C71

# python --version
Python 3.12.3

# poetry --version
Poetry (version 1.8.2)

**Comment by FlorianJacta** [comment]
Thank you! Could you try using a 3.11 Python version and tell me if it changes anything? We are working on it right now.

**Comment by figoyouwei** [comment]
Oh, the basic job run works with 3.11.4, I will play with scheduling later.

**Comment by figoyouwei** [comment]
On Python 3.11.4

`import taipy as tp`
It still returns this error, strange...

ImportError: bad magic number in 'taipy.enterprise': b'o\r\r\n'

**Comment by FlorianJacta** [comment]
What has changed from your initial run?

Taipy Enterprise, when installed, is specific to the Python version you installed it with.

**Comment by figoyouwei** [comment]
I think previously I was not running taipy Enterprise, you know vscode has kinda mistaken me. Today I installed and directly test the `import taipy as tp` from the terminal.

**Comment by FlorianJacta** [comment]
What do you use as a virtual environment?

If you have conda, do:

```
conda create -n enterprise python=3.11
conda activate enterprise
pip install "<the enterprise token here>"
```

Then, this should work:
```
python
import taipy
```

**Comment by figoyouwei** [comment]
I am using poetry.

**Comment by FlorianJacta** [comment]
I am also using poetry sometimes. This shouldn't be an issue. Taipy Enterprise version can be run only with the Python version that has been installed.

You could try to install it again by creating a new environment and installing with a particular version of Python in your `pyproject.toml`.

**Comment by AlexandreSajus** [comment]
Could we get the full logs when you get this error? We'll send this to R&D to take a look

**Comment by figoyouwei** [comment]
this is my mac
![Uploading Screenshot 2024-08-29 at 21.11.38.png…]()

**Comment by figoyouwei** [comment]
this is my mac
<img width="268" alt="Screenshot 2024-08-29 at 21 11 38" src="https://github.com/user-attachments/assets/c58bbf16-1b9c-4fe4-b97e-01e314b34624">

**Comment by figoyouwei** [comment]
python is installed via pyenv
pyenv install 3.11.4

**Comment by figoyouwei** [comment]
When this week, can we try this again on my MacOS? 
Of course, I plan also to try this in some Linux machine and give you feedbacks later in parallel, but Mac has to work...

**Comment by FlorianJacta** [comment]
We have reproduced and investigated the issue. This is indeed an issue on Poetry side. You can solve it using the same Python version in your project as your base Python environment.

Taipy Enterprise now works fine with Python 3.12.

**Comment by figoyouwei** [comment]
So what's next? I don't use Poetry and try to move on with pip?

**Comment by FlorianJacta** [comment]
We have sometimes made it work with Poetry, but Poetry doesn't manage Python versions, which creates issues.

I advise using normal pip in a conda env, venv, or any other virtual environment. If you have any issues, let's have a call together to finally fix this.

**Comment by figoyouwei** [comment]
I am using pyenv to manage Python version, and Poetry for packages. I don't use pip anymore. I mean I could try pip to make test run, but for the long term, poetry has to work...

**Comment by figoyouwei** [comment]
It is working with uv pip install.
